### ISSUE TITLE
Pasting text makes the component crash

### ISSUE THREAD

**Issue by agfernan** [prabhuignoto/smart-tagz#13]
**How to reproduce**
Paste the following text on the codesandbox
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam congue massa accumsan accumsan fringilla. Fusce tempor, ipsum non mollis pellentesque, lorem mauris posuere sapien, lacinia placerat metus enim et nulla. Donec lacinia purus vel blandit dictum. Quisque gravida dictum sagittis. Curabitur vitae nulla magna. Integer fringilla nisi eget tellus laoreet dignissim vitae eget est. Vestibulum facilisis ultrices magna, sit amet convallis neque scelerisque id. Nulla accumsan velit sit amet vestibulum condimentum. Proin vel lorem id ipsum convallis porta non sed enim. Nunc faucibus odio scelerisque tortor interdum hendrerit. Sed consequat nisi non eleifend sodales.

It throws the following error:
```
TypeError:
Cannot read property 'delimiter' of null
Proxy.handlePaste
https://pd32g.csb.app/node_modules/smart-tagz/dist/smart-tagz.esm.js:527:72
e.tagsData.length.e.maxTags.e.readOnly.onPaste.n.<computed>.n.<computed>
https://pd32g.csb.app/node_modules/smart-tagz/dist/smart-tagz.esm.js:611:49
    at callWithErrorHandling (https://pd32g.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.esm-bundler.js:801:18
    at callWithAsyncErrorHandling (https://pd32g.csb.app/node_modules/
vue/runtime-core/dist/runtime-core.esm-bundler.js:809:17
    at HTMLInputElement.invoker (https://pd32g.csb.app/node_modules/
vue/runtime-dom/dist/runtime-dom.esm-bundler.js:346:56
```

**Comment by prabhuignoto** [comment]
@agfernan this has been fixed in 0.3. please check and report if there are still any issues
