### ISSUE TITLE
bug in default-tags when passing vue data 

### ISSUE THREAD

**Issue by te-lyhourt** [prabhuignoto/smart-tagz#15]
i have an array name defaultData ,  i tried to do sth like :default-tags = "defaultData" , i noticed that it read the array into default-tags , but the tagsData doesnt read the data
![Screenshot 2021-08-19 113427](https://user-images.githubusercontent.com/74485952/130008570-d0531e93-04c5-4072-90fe-a9624c625e97.png)

**Comment by te-lyhourt** [comment]
![Uploading 1111.png…]()

**Comment by te-lyhourt** [comment]
![Uploading 1111.png…]()

**Comment by jiananxu** [comment]
I have a same problem
