### ISSUE TITLE
Styling Props

### ISSUE THREAD

**Issue by FahadHussain2020** [prabhuignoto/smart-tagz#38]
Do we have more options for the styling props other than the mentioned ones here?
`<smart-tagz class="form-control keyword-input" 
          input-placeholder="Search For Keywords" 
          :on-changed="handleChangeTag"
          :theme="{
            primary: '#f1f5f9',
            background: '#bdbdbd',
            tagTextColor: '#000',
          }"
        />`
Currently, we have only these 3 styling props.

**Comment by prabhuignoto** [comment]
@FahadHussain2020  right now these are the only available props, can you briefly describe the elements you want to customize

**Comment by FahadHussain2020** [comment]
Ahan! Okay, @prabhuignoto  actually I was looking to make it more customizable for example, we can also tweak the border radius for the tags, we can modify the "cross-icon's" color/background, and we can also change the bg-color of the tags while removing the tags with the "backspace key". I hope you are getting my point. It will be more suitable for the devs as sometimes we have to go with the color scheme for the website.

**Comment by prabhuignoto** [comment]
sounds like what we need here is the ability to add custom class names to the elements. this will be added to the next minor release.

**Comment by FahadHussain2020** [comment]
Yeah sure, that'll be great! Thanks!

**Comment by prabhuignoto** [comment]
you can now apply custom class names using the `classNames` prop. something like this

```jsx
<smart-tagz
  input-placeholder="Select Countries ..."
  :class-names="{
    wrapper: 'tags_wrapper_custom',
    tag_name: 'tag_name_custom',
    tag_container: 'tag_container_custom',
    tag_close_btn: 'tag_close_btn_custom',
  }"
  :default-tags="[
    'United Kingdom',
    'Uruguay',
    'Uzbekistan',
    'Venezuela'
  ]"
/>
```

do check and let me know how it goes for you
