### ISSUE TITLE
CSS file is missing for newer version (0.4.0)

### ISSUE THREAD

**Issue by afduarte** [prabhuignoto/smart-tagz#44]
When trying to import the css file like the documentation suggests:

```
import "smart-tagz/dist/smart-tagz.css";
```

The import fails and the file is not found. Upon inspecting the `node_modules` directory, the css file is not there, instead the only css file is in the assets/ directory, called output-{hash}.css

Downgrading to version 0.3.2 fixed this for me

**Comment by prabhuignoto** [comment]
@afduarte thanks for opening the issue. this is now fixes with the patch release. do check out and let me know if you still face issues

**Comment by afduarte** [comment]
That seems to have fixed it, thanks!
