### ISSUE TITLE
Changing size of tags

### ISSUE THREAD

**Issue by john-** [prabhuignoto/smart-tagz#48]
I expect this is a general html/css question so please feel free to give general pointers.

Ideally I want to make the tags smaller but starting with color changing.  I have this in my .vue file but nothing changes in the `<smart-tagz>` in the template:
```
<style scoped>
.smart-tagz {
  color: green;
  background-color: orange;
}
</style>
```
What am I missing?

**Comment by john-** [comment]
I see now in docs how to change color via `theme`.  How about the size?

**Comment by john-** [comment]
It i probably via [custom class names](https://github.com/prabhuignoto/smart-tagz#custom-class-names). If anyone has an example of how to use this it would be appreciated. I can share what I have so far that doesn't work.

**Comment by prabhuignoto** [comment]
@john- did you try using the class names?

**Comment by john-** [comment]
I have not been able to figure out how to use custom class names.  If someone has a handy example of how to use them in a Vue application that would be great.   In any case I will close the ticket in a day or so.

**Comment by john-** [comment]
Thanks for confirming how to change the size.  As this is now a Vue related item this ticket is being closed.
