### ISSUE TITLE
How get data ?

### ISSUE THREAD

**Issue by zokiasu** [prabhuignoto/smart-tagz#5]
Hi, i'm new with vue but i tried to use your component and I don't understand how I can get data when I add a new tag.
can you explain how we can do that please ?

**Comment by prabhuignoto** [comment]
@Zokiasu  thanks for flagging this.

now the component has a new prop `on-changed` to receive the tag data in the form of array. The `on-changed` prop will be called when a new tag is added or an existing tag is deleted.

### Usage example

```sh
<template>
  <div class="example">
    <div class="sample-view">
      <smart-tagz
        input-placeholder="Select Countries ..."
        :on-changed="logResult"
      />
    </div>
  </div>
</template>


<script>
import SmartTagz from "smart-tagz";

import { defineComponent } from "vue";

export default defineComponent({
  name: "Basic",
  components: {
    SmartTagz,
  },
  setup() {
    const logResult = (result: string[]) => console.log(result);

    return {
      logResult,
    };
  },
});
</script>
```

please update the lib and let me know how it works out for you.

**Comment by zokiasu** [comment]
Thanks you @prabhuignoto ! All work fine !
