### ISSUE TITLE
How to access tags?

### ISSUE THREAD

**Issue by lightscalar** [prabhuignoto/smart-tagz#8]
Excellent library, but I cannot for the life of me figure out how to access the tags that are created. There seem to be no examples in the documentation or examples where the tags are exposed to the external application.

I figured I could write something like `<smart-tagz v-model="tags" />` and this would update my application's local `tags` variable, but this doesn't seem to be the case. Looking through the source code, I cannot figure out what prop (if any) exposes the tag contents.

Could you provide an example of how to get a two-way binding with an external tags array?

**Comment by prabhuignoto** [comment]
@lightscalar  the `on-change` callback can be used to fetch the selected tags. i will add an example fairly soon.

can you give it a try and let me know how it works for you

https://github.com/prabhuignoto/smart-tagz#props

**Comment by lightscalar** [comment]
Okay, that did work. I had tried this previously, but was treating it as an event, rather than a prop. That is, I was adding `@on-changed="..."` rather than `:on-changed`, despite it clearly being listed as a prop.

I notice that the callback is fired when a tag is added or deleted by clicking on a tag's "X" button, but it is not fired when using the delete key to delete a tag, nor is it fired when a tag is edited. Perhaps a bug?

Also, one final question: is the intended way to get tags INTO a `<smart-tagz />` component via the `default-tags` prop?

**Comment by codingcronus** [comment]
> I notice that the callback is fired when a tag is added or deleted by clicking on a tag's "X" button, but it is not fired when using the delete key to delete a tag, nor is it fired when a tag is edited. Perhaps a bug?

I also experience the same behaviour.

**Comment by prabhuignoto** [comment]
@lightscalar @codingcronus the callback will now fire for all changes, edit, delete etc. please do check out in the latest version (0.3.0).

> Also, one final question: is the intended way to get tags INTO a <smart-tagz /> component via the default-tags prop?

Thats right you need to use the default tags for settings the tags
