### ISSUE TITLE
Invalid regular expression

### ISSUE THREAD

**Issue by raimondslindezutzu** [prabhuignoto/smart-tagz#9]
`smart-tagz.esm.js:4 Uncaught (in promise) SyntaxError: Invalid regular expression: /^c++$/: Nothing to repeat
    at new RegExp (<anonymous>)`

Trying to add a tag: c++ throws me an error, also unable to select c++ from sources

**Comment by raimondslindezutzu** [comment]
This issue can be fixed by escaping "+" character:

`var e = new RegExp("^" + h.value.replaceAll('\+', '\\+'), "i");`

and

`var n = new RegExp("^" + e.replaceAll('\+', '\\+') + "$", "ig"), t = a || !p.value.some((function (t) {`

**Comment by sheoak** [comment]
I fixed it in our organisation fork, because I don't have time to wait for a pull request to be merged, but I will also make a new PR on this repo.

https://www.npmjs.com/package/@genario/smart-tagz

`yarn add @genario/smart-tagz`
or 
`npm install --save  @genario/smart-tagz`
